CREATE TABLE MALLZELLIJ.YDEVISMOBILE (
    ROWID      NUMERIC IDENTITY(1,1) PRIMARY KEY,
    UPDTICK_0  INT,
    YSITE_0    NVARCHAR(10),
    YBPCNUM_0  NVARCHAR(20),
    YBPCNAM_0  NVARCHAR(100),
    YITMREF_0  NVARCHAR(30),
    YITMDES_0  NVARCHAR(200),
    YQTY_0     NUMERIC(20,4),
    YPRICE_0   NUMERIC(20,4),
    YCOEFF_0   NUMERIC(20,4),
    YCARTON_0  INT,
    CREDATTIM_0 DATETIME,
    UPDDATTIM_0 DATETIME,
    AUUID_0    BINARY(16),
    CREUSR_0   NVARCHAR(20),
    UPDUSR_0   NVARCHAR(20)
);
