spring.datasource.url=jdbc:jtds:sqlserver://SERVEURX3;instance=X3V11;databaseName=x3v11

spring.datasource.username=mobile
spring.datasource.password=Dev@2026
spring.datasource.driver-class-name=net.sourceforge.jtds.jdbc.Driver
spring.datasource.hikari.connection-test-query=SELECT 1

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=MALLZELLIJ
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
server.port=8070
spring.jpa.open-in-view=false
